### ISSUE TITLE
`RetroLogger` cannot filter output by scope

### ISSUE THREAD

**Issue by JesseTG** [max-m/rust-libretro#3]
Because of how `RetroLogger` is initialized, any logging output made with `log!()` is forwarded to the RetroArch log. This is a good thing; however, some Rust crates are a bit excessive. They might use `debug!()` when `trace!()` would've been more appropriate. Or perhaps I'm just not interested in what they have to say. See [this log file](https://github.com/max-m/rust-libretro/files/10346589/retroarch.log) for an example. For the purpose of this ticket, the _contents_ of the log file are unimportant; just note that there's a lot of repetitive input that I don't care about.

I'd like (and intend to contribute) the ability to configure overrides with `RetroLogger`, such that scopes can be disabled or mapped to different log levels. Here's what I'm thinking:

1. Expose `RetroLogger` `pub`licly so that it can be customized if the default behavior isn't desired (and so that existing usage is unchanged)
2. Provide a `RetroLogger` method that's used something like this:

```rust
logger.set_overrides(HashMap::from([
    ("naga::*", Mute), // Ignore all output from the naga scope and it's sub-scopes
    ("wgpu_core::track::texture", Remap(log::Level::Debug, log::Level::Trace), // Force all debug output from wgpu_core::track::texture to be outputted as trace logs instead
    ("wgpu_core::device", Force(log::Level::Trace)), // Force all output from wgpu_core::device to be outputted as trace logs
    ("something_else", Remap(log::Level::Warn, log::Level::Error), // Force all warn output from something_else to be outputted as error logs
]))
```

This particular design is just a back-of-the-napkin idea. What do you think?

**Comment by max-m** [comment]
Hi Jesse,
for now I chose the easy route and re-used `env_logger`s powerful filter builder.
See https://github.com/max-m/rust-libretro/commit/6a2b6f50e5f021183ab4c42e50c77b811186cb55.
Unless the `RUST_LOG` environment variable is set everything should behave as it did previously.
When the variable is set log messages will be filtered according to the rules of `env_logger`:
https://docs.rs/env_logger/latest/env_logger/#enabling-logging and https://docs.rs/env_logger/latest/env_logger/#filtering-results

**Comment by JesseTG** [comment]
Oh, wow, I had no idea that was a thing. Thanks!
